### ISSUE TITLE
Case vide pas trouvée automatiquement

### ISSUE THREAD

**Issue by Ahcamn** [Ahcamn/Althacamn-F3#5]
Problème : On doit indiquer l'emplacement de la case vide puise l'endroit où la déplacer. Il faudrait que le programme trouve tout seul l'emplacement de la case vide.

Comment reproduire le bug ?
Choisir le choix 2 (Déplacer la case vide).

**Comment by Altharos** [comment]
fonction qui trouve la case vide créée, autre problème engendré
